name: kurigram

on: [push]

jobs:
  cd:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      run:  |
        docker build -t ${{ secrets.DOCKER_USER }}/kurigram:${{ github.sha }} .
        docker build -t ${{ secrets.DOCKER_USER }}/kurigram:latest .
    - name: Push
      run: |
          docker push ${{ secrets.DOCKER_USER }}/kurigram:${{ github.sha }}
          docker push ${{secrets.DOCKER_USER}}/kurigram:latest
